spring.application.name=estoque-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/estoque}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:estoque}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:estoque}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.port=8080